# Generated by Django 4.2.3 on 2023-07-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='aboutOfBook',
            field=models.CharField(default='Yet to know.', max_length=2128),
        ),
        migrations.AddField(
            model_name='books',
            name='priceofBook',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='books',
            name='publisherName',
            field=models.CharField(default='Yet to know.', max_length=255),
        ),
        migrations.AddField(
            model_name='books',
            name='ratingOfBook',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='books',
            name='releaseDate',
            field=models.DateField(null=True),
        ),
    ]
