# Generated by Django 4.2.3 on 2023-07-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_aboutofbook_books_priceofbook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='genreOfBook',
            field=models.CharField(default='Yet to know.', max_length=255),
        ),
    ]
