# -*- coding: utf-8 -*-
"""csv_generation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ecGgiR-0MyzDjfdDYeL0s96IJGg5Iemh
"""

import pandas as pd
import random as rn
import string

df = pd.DataFrame()

book_name_min_lenght = 10
book_name_max_lenght = 30

writer_first_name_min_length = 5
writer_last_name_min_lenght = 5
writer_first_name_max_length = 10
writer_last_name_max_lenght = 10

number_of_books = 400000
for i in range(0,number_of_books):

  b_n_l = rn.randint(book_name_min_lenght,book_name_max_lenght)
  w_fn_l = rn.randint(writer_first_name_min_length,writer_first_name_max_length)
  w_ln_l = rn.randint(writer_last_name_min_lenght,writer_last_name_max_lenght)

  a_book_name = ''.join(rn.choices(string.ascii_uppercase + string.digits, k=b_n_l))
  a_writer_name = ''.join(rn.choices(string.ascii_uppercase, k=w_fn_l)) + '_' + ''.join(rn.choices(string.ascii_uppercase, k=w_ln_l))

  temp = pd.DataFrame([
            {
      'id' : i+8,
      'name' : a_book_name,
      'writer' : a_writer_name,
      'rating' : round(rn.uniform(0.00,10.00),2),
      #'price' : rn.randint(50,10000),
      'price' : round(rn.uniform(50.00,10000.00),2),
      'link' : 'httpp:test_flag_eblict'
  }
  ]

  )
  #print(temp)
  df = pd.concat([df, temp])

print(df.size)

df.to_csv('dummy_books.csv',index=False)