# Generated by Django 4.2.4 on 2023-08-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
